/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Account {
    /**
     * List of the users in the account
     */
    
    public String[] accountUsers;
    public Account withAccountUsers(String[] accountUsers) {
        this.accountUsers = accountUsers;
        return this;
    }
    
    /**
     * Timestamp of the account creation date
     */
    
    public String createdAt;
    public Account withCreatedAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * The id of the account
     */
    
    public Double id;
    public Account withId(Double id) {
        this.id = id;
        return this;
    }
    
    /**
     * The name of the account
     */
    
    public String name;
    public Account withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The id of the account owner
     */
    
    public Double ownerId;
    public Account withOwnerId(Double ownerId) {
        this.ownerId = ownerId;
        return this;
    }
    
    /**
     * If the account is personal or belonging to another account
     */
    
    public Boolean personal;
    public Account withPersonal(Boolean personal) {
        this.personal = personal;
        return this;
    }
    
    /**
     * Timestamp of the last account update date
     */
    
    public String updatedAt;
    public Account withUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    

    public Account(@JsonProperty("account_users") String[] accountUsers, @JsonProperty("created_at") String createdAt, @JsonProperty("id") Double id, @JsonProperty("name") String name, @JsonProperty("owner_id") Double ownerId, @JsonProperty("personal") Boolean personal, @JsonProperty("updated_at") String updatedAt) {
    this.accountUsers = accountUsers;
this.createdAt = createdAt;
this.id = id;
this.name = name;
this.ownerId = ownerId;
this.personal = personal;
this.updatedAt = updatedAt;
  }
}
