/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.shared;



/**
 * Person - returns the person
 */
public class Person {
    /**
     * The birth date of the person
     */
    
    public String birthDate;
    public Person withBirthDate(String birthDate) {
        this.birthDate = birthDate;
        return this;
    }
    
    /**
     * The birth year of the person
     */
    
    public Double birthYear;
    public Person withBirthYear(Double birthYear) {
        this.birthYear = birthYear;
        return this;
    }
    
    /**
     * The certifications of the person
     */
    
    public String[] certifications;
    public Person withCertifications(String[] certifications) {
        this.certifications = certifications;
        return this;
    }
    
    /**
     * The educational history of the person
     */
    
    public String[] education;
    public Person withEducation(String[] education) {
        this.education = education;
        return this;
    }
    
    /**
     * The personal and work emails of the person
     */
    
    public String[] emails;
    public Person withEmails(String[] emails) {
        this.emails = emails;
        return this;
    }
    
    /**
     * The works experience of the person
     */
    
    public String[] experience;
    public Person withExperience(String[] experience) {
        this.experience = experience;
        return this;
    }
    
    /**
     * The Facebook ID of the person
     */
    
    public String facebookId;
    public Person withFacebookId(String facebookId) {
        this.facebookId = facebookId;
        return this;
    }
    
    /**
     * The Facebook URL of the person
     */
    
    public String facebookUrl;
    public Person withFacebookUrl(String facebookUrl) {
        this.facebookUrl = facebookUrl;
        return this;
    }
    
    /**
     * The Facebook username of the person
     */
    
    public String facebookUsername;
    public Person withFacebookUsername(String facebookUsername) {
        this.facebookUsername = facebookUsername;
        return this;
    }
    
    /**
     * The first name of the person
     */
    
    public String firstName;
    public Person withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    /**
     * The full name of the person
     */
    
    public String fullName;
    public Person withFullName(String fullName) {
        this.fullName = fullName;
        return this;
    }
    
    /**
     * The gender of the person
     */
    
    public String gender;
    public Person withGender(String gender) {
        this.gender = gender;
        return this;
    }
    
    /**
     * The Github URL of the person
     */
    
    public String githubUrl;
    public Person withGithubUrl(String githubUrl) {
        this.githubUrl = githubUrl;
        return this;
    }
    
    /**
     * The Github username of the person
     */
    
    public String githubUsername;
    public Person withGithubUsername(String githubUsername) {
        this.githubUsername = githubUsername;
        return this;
    }
    
    /**
     * The key for looking up the company
     */
    
    public Double id;
    public Person withId(Double id) {
        this.id = id;
        return this;
    }
    
    /**
     * The industry of the person
     */
    
    public String industry;
    public Person withIndustry(String industry) {
        this.industry = industry;
        return this;
    }
    
    /**
     * The inferred salary band for the person
     */
    
    public String inferredSalary;
    public Person withInferredSalary(String inferredSalary) {
        this.inferredSalary = inferredSalary;
        return this;
    }
    
    /**
     * The inferred years of experience for the person
     */
    
    public Double inferredYearsExperience;
    public Person withInferredYearsExperience(Double inferredYearsExperience) {
        this.inferredYearsExperience = inferredYearsExperience;
        return this;
    }
    
    /**
     * The interests of the person
     */
    
    public String[] interests;
    public Person withInterests(String[] interests) {
        this.interests = interests;
        return this;
    }
    
    /**
     * The current job company Facebook URL
     */
    
    public String jobCompanyFacebookUrl;
    public Person withJobCompanyFacebookUrl(String jobCompanyFacebookUrl) {
        this.jobCompanyFacebookUrl = jobCompanyFacebookUrl;
        return this;
    }
    
    /**
     * The current job company founded year
     */
    
    public String jobCompanyFounded;
    public Person withJobCompanyFounded(String jobCompanyFounded) {
        this.jobCompanyFounded = jobCompanyFounded;
        return this;
    }
    
    /**
     * The current job company ID
     */
    
    public String jobCompanyId;
    public Person withJobCompanyId(String jobCompanyId) {
        this.jobCompanyId = jobCompanyId;
        return this;
    }
    
    /**
     * The current job company industry
     */
    
    public String jobCompanyIndustry;
    public Person withJobCompanyIndustry(String jobCompanyIndustry) {
        this.jobCompanyIndustry = jobCompanyIndustry;
        return this;
    }
    
    /**
     * The current job company id on LinkedIn
     */
    
    public String jobCompanyLinkedinId;
    public Person withJobCompanyLinkedinId(String jobCompanyLinkedinId) {
        this.jobCompanyLinkedinId = jobCompanyLinkedinId;
        return this;
    }
    
    /**
     * The current job company LinkedIn URL
     */
    
    public String jobCompanyLinkedinUrl;
    public Person withJobCompanyLinkedinUrl(String jobCompanyLinkedinUrl) {
        this.jobCompanyLinkedinUrl = jobCompanyLinkedinUrl;
        return this;
    }
    
    /**
     * The current job company location street adress second line
     */
    
    public String jobCompanyLocationAddressLine2;
    public Person withJobCompanyLocationAddressLine2(String jobCompanyLocationAddressLine2) {
        this.jobCompanyLocationAddressLine2 = jobCompanyLocationAddressLine2;
        return this;
    }
    
    /**
     * The current job company location continent
     */
    
    public String jobCompanyLocationContinent;
    public Person withJobCompanyLocationContinent(String jobCompanyLocationContinent) {
        this.jobCompanyLocationContinent = jobCompanyLocationContinent;
        return this;
    }
    
    /**
     * The current job company location country
     */
    
    public String jobCompanyLocationCountry;
    public Person withJobCompanyLocationCountry(String jobCompanyLocationCountry) {
        this.jobCompanyLocationCountry = jobCompanyLocationCountry;
        return this;
    }
    
    /**
     * The current job company location geo coordinates
     */
    
    public String jobCompanyLocationGeo;
    public Person withJobCompanyLocationGeo(String jobCompanyLocationGeo) {
        this.jobCompanyLocationGeo = jobCompanyLocationGeo;
        return this;
    }
    
    /**
     * The current job company location city
     */
    
    public String jobCompanyLocationLocality;
    public Person withJobCompanyLocationLocality(String jobCompanyLocationLocality) {
        this.jobCompanyLocationLocality = jobCompanyLocationLocality;
        return this;
    }
    
    /**
     * The current job company location metro
     */
    
    public String jobCompanyLocationMetro;
    public Person withJobCompanyLocationMetro(String jobCompanyLocationMetro) {
        this.jobCompanyLocationMetro = jobCompanyLocationMetro;
        return this;
    }
    
    /**
     * The current job company location name
     */
    
    public String jobCompanyLocationName;
    public Person withJobCompanyLocationName(String jobCompanyLocationName) {
        this.jobCompanyLocationName = jobCompanyLocationName;
        return this;
    }
    
    /**
     * The current job company location postal code
     */
    
    public String jobCompanyLocationPostalCode;
    public Person withJobCompanyLocationPostalCode(String jobCompanyLocationPostalCode) {
        this.jobCompanyLocationPostalCode = jobCompanyLocationPostalCode;
        return this;
    }
    
    /**
     * The current job company location region
     */
    
    public String jobCompanyLocationRegion;
    public Person withJobCompanyLocationRegion(String jobCompanyLocationRegion) {
        this.jobCompanyLocationRegion = jobCompanyLocationRegion;
        return this;
    }
    
    /**
     * The current job company location street address
     */
    
    public String jobCompanyLocationStreetAddress;
    public Person withJobCompanyLocationStreetAddress(String jobCompanyLocationStreetAddress) {
        this.jobCompanyLocationStreetAddress = jobCompanyLocationStreetAddress;
        return this;
    }
    
    /**
     * The current job company name
     */
    
    public String jobCompanyName;
    public Person withJobCompanyName(String jobCompanyName) {
        this.jobCompanyName = jobCompanyName;
        return this;
    }
    
    /**
     * The current job company size
     */
    
    public String jobCompanySize;
    public Person withJobCompanySize(String jobCompanySize) {
        this.jobCompanySize = jobCompanySize;
        return this;
    }
    
    /**
     * The current job company Twitter URL
     */
    
    public String jobCompanyTwitterUrl;
    public Person withJobCompanyTwitterUrl(String jobCompanyTwitterUrl) {
        this.jobCompanyTwitterUrl = jobCompanyTwitterUrl;
        return this;
    }
    
    /**
     * The current job company website
     */
    
    public String jobCompanyWebsite;
    public Person withJobCompanyWebsite(String jobCompanyWebsite) {
        this.jobCompanyWebsite = jobCompanyWebsite;
        return this;
    }
    
    /**
     * The last update date for the job
     */
    
    public String jobLastUpdated;
    public Person withJobLastUpdated(String jobLastUpdated) {
        this.jobLastUpdated = jobLastUpdated;
        return this;
    }
    
    /**
     * The start date for the current job
     */
    
    public String jobStartDate;
    public Person withJobStartDate(String jobStartDate) {
        this.jobStartDate = jobStartDate;
        return this;
    }
    
    /**
     * The summary for the current job
     */
    
    public String jobSummary;
    public Person withJobSummary(String jobSummary) {
        this.jobSummary = jobSummary;
        return this;
    }
    
    /**
     * The current job title of the person
     */
    
    public String jobTitle;
    public Person withJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
        return this;
    }
    
    /**
     * The current job title levels
     */
    
    public String[] jobTitleLevels;
    public Person withJobTitleLevels(String[] jobTitleLevels) {
        this.jobTitleLevels = jobTitleLevels;
        return this;
    }
    
    /**
     * The current job title role of the person
     */
    
    public String jobTitleRole;
    public Person withJobTitleRole(String jobTitleRole) {
        this.jobTitleRole = jobTitleRole;
        return this;
    }
    
    /**
     * The current job title sub-role of the person
     */
    
    public String jobTitleSubRole;
    public Person withJobTitleSubRole(String jobTitleSubRole) {
        this.jobTitleSubRole = jobTitleSubRole;
        return this;
    }
    
    /**
     * The languages of the person
     */
    
    public String[] languages;
    public Person withLanguages(String[] languages) {
        this.languages = languages;
        return this;
    }
    
    /**
     * The last name of the person
     */
    
    public String lastName;
    public Person withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    /**
     * The number of LinkedIn connections for the person
     */
    
    public Double linkedinConnections;
    public Person withLinkedinConnections(Double linkedinConnections) {
        this.linkedinConnections = linkedinConnections;
        return this;
    }
    
    /**
     * The linkedIn ID of the person
     */
    
    public Double linkedinId;
    public Person withLinkedinId(Double linkedinId) {
        this.linkedinId = linkedinId;
        return this;
    }
    
    /**
     * The linkedIn URL of the person
     */
    
    public String linkedinUrl;
    public Person withLinkedinUrl(String linkedinUrl) {
        this.linkedinUrl = linkedinUrl;
        return this;
    }
    
    /**
     * The linkedIn user name of the person
     */
    
    public String linkedinUsername;
    public Person withLinkedinUsername(String linkedinUsername) {
        this.linkedinUsername = linkedinUsername;
        return this;
    }
    
    /**
     * The current location street address second line for the person
     */
    
    public String locationAddressLineTwo;
    public Person withLocationAddressLineTwo(String locationAddressLineTwo) {
        this.locationAddressLineTwo = locationAddressLineTwo;
        return this;
    }
    
    /**
     * The current location continent for the person
     */
    
    public String locationContinent;
    public Person withLocationContinent(String locationContinent) {
        this.locationContinent = locationContinent;
        return this;
    }
    
    /**
     * The current location country for the person
     */
    
    public String locationCountry;
    public Person withLocationCountry(String locationCountry) {
        this.locationCountry = locationCountry;
        return this;
    }
    
    /**
     * The current location geo coordinates for the person
     */
    
    public String[] locationGeo;
    public Person withLocationGeo(String[] locationGeo) {
        this.locationGeo = locationGeo;
        return this;
    }
    
    /**
     * The current location last updated date for the person
     */
    
    public String locationLastUpdated;
    public Person withLocationLastUpdated(String locationLastUpdated) {
        this.locationLastUpdated = locationLastUpdated;
        return this;
    }
    
    /**
     * The current location city for the person
     */
    
    public String locationLocality;
    public Person withLocationLocality(String locationLocality) {
        this.locationLocality = locationLocality;
        return this;
    }
    
    /**
     * The current location metro for the person
     */
    
    public String locationMetro;
    public Person withLocationMetro(String locationMetro) {
        this.locationMetro = locationMetro;
        return this;
    }
    
    /**
     * The current location name for the person
     */
    
    public String locationName;
    public Person withLocationName(String locationName) {
        this.locationName = locationName;
        return this;
    }
    
    /**
     * The current location postal code for the person
     */
    
    public String locationPostalCode;
    public Person withLocationPostalCode(String locationPostalCode) {
        this.locationPostalCode = locationPostalCode;
        return this;
    }
    
    /**
     * The current location region for the person
     */
    
    public String locationRegion;
    public Person withLocationRegion(String locationRegion) {
        this.locationRegion = locationRegion;
        return this;
    }
    
    /**
     * The current location street address for the person
     */
    
    public String locationStreetAddress;
    public Person withLocationStreetAddress(String locationStreetAddress) {
        this.locationStreetAddress = locationStreetAddress;
        return this;
    }
    
    /**
     * The middle initial of the person
     */
    
    public String middleInitial;
    public Person withMiddleInitial(String middleInitial) {
        this.middleInitial = middleInitial;
        return this;
    }
    
    /**
     * The middle name of the person
     */
    
    public String middleName;
    public Person withMiddleName(String middleName) {
        this.middleName = middleName;
        return this;
    }
    
    /**
     * The mobile phone of the person
     */
    
    public String mobilePhone;
    public Person withMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
        return this;
    }
    
    /**
     * The phone numbers of the person
     */
    
    public String[] phoneNumbers;
    public Person withPhoneNumbers(String[] phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
        return this;
    }
    
    /**
     * The social profiles of the person
     */
    
    public String[] profiles;
    public Person withProfiles(String[] profiles) {
        this.profiles = profiles;
        return this;
    }
    
    /**
     * The skills of the person
     */
    
    public String[] skills;
    public Person withSkills(String[] skills) {
        this.skills = skills;
        return this;
    }
    
    /**
     * The street addresses of the person
     */
    
    public String[] streetAddresses;
    public Person withStreetAddresses(String[] streetAddresses) {
        this.streetAddresses = streetAddresses;
        return this;
    }
    
    /**
     * The self-summary of the person's work experience
     */
    
    public String summary;
    public Person withSummary(String summary) {
        this.summary = summary;
        return this;
    }
    
    /**
     * The Twitter URL of the person
     */
    
    public String twitterUrl;
    public Person withTwitterUrl(String twitterUrl) {
        this.twitterUrl = twitterUrl;
        return this;
    }
    
    /**
     * The Twitter username of the person
     */
    
    public String twitterUsername;
    public Person withTwitterUsername(String twitterUsername) {
        this.twitterUsername = twitterUsername;
        return this;
    }
    
    /**
     * The work email of the person
     */
    
    public String workEmail;
    public Person withWorkEmail(String workEmail) {
        this.workEmail = workEmail;
        return this;
    }
    
}
