/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AuthsApplicationJSON {
    /**
     * The email of the user
     */
    @JsonProperty("email")
    public String email;
    public AuthsApplicationJSON withEmail(String email) {
        this.email = email;
        return this;
    }
    
    /**
     * The password of the user
     */
    @JsonProperty("password")
    public String password;
    public AuthsApplicationJSON withPassword(String password) {
        this.password = password;
        return this;
    }
    
}
