/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;



public class CompanyJobsRequest {
    public CompanyJobsPathParams pathParams;
    public CompanyJobsRequest withPathParams(CompanyJobsPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
    public CompanyJobsQueryParams queryParams;
    public CompanyJobsRequest withQueryParams(CompanyJobsQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
