/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;



public class CompanyEmployeesRequest {
    public CompanyEmployeesPathParams pathParams;
    public CompanyEmployeesRequest withPathParams(CompanyEmployeesPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
    public CompanyEmployeesQueryParams queryParams;
    public CompanyEmployeesRequest withQueryParams(CompanyEmployeesQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
