/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import structure.Structure.utils.SpeakeasyMetadata;

public class EnrichPersonRequest {
    /**
     * LinkedIn ID of the person
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public EnrichPersonRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public EnrichPersonRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
