/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;



public class EnrichPersonRequest {
    public EnrichPersonQueryParams queryParams;
    public EnrichPersonRequest withQueryParams(EnrichPersonQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
