/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;

import structure.Structure.utils.SpeakeasyMetadata;

public class EnrichCompanyQueryParams {
    /**
     * Country code of the company
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=country_code")public String countryCode;
    public EnrichCompanyQueryParams withCountryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }
    
    /**
     * The headquarters of the company
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=headquarters")public String headquarters;
    public EnrichCompanyQueryParams withHeadquarters(String headquarters) {
        this.headquarters = headquarters;
        return this;
    }
    
    /**
     * ID of the company
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=id")public String id;
    public EnrichCompanyQueryParams withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * Game of the company
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=name")public String name;
    public EnrichCompanyQueryParams withName(String name) {
        this.name = name;
        return this;
    }
    
}
