/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;



public class EnrichCompanyRequest {
    public EnrichCompanyQueryParams queryParams;
    public EnrichCompanyRequest withQueryParams(EnrichCompanyQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
