/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;

import structure.Structure.utils.SpeakeasyMetadata;

public class EnrichPersonQueryParams {
    /**
     * LinkedIn ID of the person
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=id")public String id;
    public EnrichPersonQueryParams withId(String id) {
        this.id = id;
        return this;
    }
    
}
