/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import structure.Structure.utils.SpeakeasyMetadata;

public class ListEmployeesRequest {
    /**
     * ID of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;
    public ListEmployeesRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The offset number to start at
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")
    public String offset;
    public ListEmployeesRequest withOffset(String offset) {
        this.offset = offset;
        return this;
    }
    
    /**
     * Number of results per page (0-100)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=per_page")
    public String perPage;
    public ListEmployeesRequest withPerPage(String perPage) {
        this.perPage = perPage;
        return this;
    }
    

    public ListEmployeesRequest(@JsonProperty("id") String id) {
    this.id = id;
  }
}
