/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;



public class ListEmployees200Wildcard {
    public ListEmployees200Wildcard(){}
}
