/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;



public class ListJobs200Wildcard {
    public ListJobs200Wildcard(){}
}
