/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class LoginApplicationJSON {
    /**
     * The email of the user
     */
    @JsonProperty("email")
    public String email;
    public LoginApplicationJSON withEmail(String email) {
        this.email = email;
        return this;
    }
    
    /**
     * The password of the user
     */
    @JsonProperty("password")
    public String password;
    public LoginApplicationJSON withPassword(String password) {
        this.password = password;
        return this;
    }
    
    public LoginApplicationJSON(@JsonProperty("email") String email, @JsonProperty("password") String password) {
        this.email = email;
        this.password = password;
  }
}
