/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;

import structure.Structure.utils.SpeakeasyMetadata;

public class SearchSearchRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")public Object request;
    public SearchSearchRequest withRequest(Object request) {
        this.request = request;
        return this;
    }
    
}
