/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class SearchSearchApplicationJSON {
    /**
     * Filter for searching
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("filter")
    public String filter;
    public SearchSearchApplicationJSON withFilter(String filter) {
        this.filter = filter;
        return this;
    }
    
    /**
     * Number of results per page (0-100)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("limit")
    public String limit;
    public SearchSearchApplicationJSON withLimit(String limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * The offset number to start at
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("page")
    public String page;
    public SearchSearchApplicationJSON withPage(String page) {
        this.page = page;
        return this;
    }
    
    /**
     * Query for searching
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("query")
    public String query;
    public SearchSearchApplicationJSON withQuery(String query) {
        this.query = query;
        return this;
    }
    
}
