/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;



public class SearchPeople200Wildcard {
    public SearchPeople200Wildcard(){}
}
