/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package structure.Structure.models.operations;



public class SearchCompanies200Wildcard {
    public SearchCompanies200Wildcard(){}
}
